name: Production CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.x"

      - name: Clean install and build
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm audit fix
          npm run build

      - name: Run tests
        run: npm run coverage:ci || true

      - name: Publish test results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: "**/test-report.xml"

      - name: Publish code coverage results
        uses: codecov/codecov-action@v2
        with:
          file: "./coverage/cobertura-coverage.xml"
          fail_ci_if_error: true
